- firmware/signing.c
Most time in signing transaction on the Trezor side is spent
in layoutProgress.  This patch reduces the calls to this functions.
We also compute the progress differently, reserving 50 % for downloading
input transactions and 50 % for the signing process.  This gives a
smoother experience if the input transactions are large.
If you use python-trezor you should apply the following diff, which increases the polling frequency.
```
diff --git a/trezorlib/transport_hid.py b/trezorlib/transport_hid.py
--- a/trezorlib/transport_hid.py
+++ b/trezorlib/transport_hid.py
@@ -122,7 +122,7 @@ class HidTransport(Transport):
raise ConnectionError("Connection failed")
-                time.sleep(0.05)
+                time.sleep(0.0001)
continue
report_id = data[0]
```
> Faster signing, smoother progressbar.

- .gitmodules
- firmware-docker-build.sh
- firmware/Makefile
- firmware/crypto.c
- firmware/crypto.h
- firmware/fsm.c
- firmware/protob/messages.options
- firmware/protob/messages.pb.c
- firmware/protob/messages.pb.h
- firmware/signing.c
support both NIST256P1 and SECP256K1 ECDSA curves.
> enable Trezor to perform SSH public key authentication

- firmware/fsm.c
https://gcc.gnu.org/gcc-4.6/changes.html
> fsm: add compile-time assert for response size validation

- firmware/crypto.c
- firmware/fsm.c
- firmware/storage.c
- firmware/storage.h
Use different keys for different curves.
This requires the corresponding pull request in trezor-crypto and vice versa.
> Multicurve

- firmware/fsm.c
It is no longer necessary to move the public key into a temporary buffer
since the node is specific for the curve and contains the right public
key.
> Remove the public_key hack.

- firmware/coins.c
updated coins datastructure to include the new fields
> fix compilation

- bootloader/bootloader.h
- bootloader/usb.c
Compute sha256 hashsum at the end.
Display progress bar for flash erase.
> Bootloader update: Faster flashing, smoother animation.

- firmware/storage.c
Storage restore was broken due to my previous patch.
> Bugfix: restore storage.

- firmware/protob/messages.options
- firmware/protob/messages.pb.c
- firmware/protob/messages.pb.h
The following commit will add a new handler for the `GetECDHSessionKey` request (#85).
> Update protobuf definitions

- firmware/fsm.c
- firmware/layout2.c
- firmware/layout2.h
Also fix the message "abort" to send a reply (an ActionCancelled failure)
> Ask for confirmation on ECDH Session (gpg decrypt)

- firmware/coins.c
Address_type and address_type_p2sh were switched
> Switching address types

- firmware/crypto.c
Now we can support larger digests (e.g. SHA-512) in [GPG signatures](https://github.com/romanz/trezor-agent/commit/2d6efd4302e1b6ede1b3897ccb113bd3b17eb966).
> crypto: allow Ed25519 signing larger digests

- firmware/trezor.c
> Fix screen timeout

- Makefile.include
Should no longer require clean builds during development
> Generate dependency files

- firmware/usb.c
Interfaces are virtually unlimited, using the same endpoint for both
interfaces frees up an extra endpoint.
This has the disadvantage that claiming the WebUSB interface, also
"claims" the HID interface. This is, however, a far more appealing
disadvantage than the loss of that endpoint altogether.
> WebUSB: Deduplicate endpoint

- firmware/ethereum.c
- firmware/protob/messages.pb.c
- firmware/protob/messages.pb.h
- Allow some edge cases  #143.
- Added EIP-155 replay protection #142.
> Ethereum updates

- firmware/Makefile
> Reduce firmware size by removing duplicate basepoint tables

- firmware/ethereum.c
- firmware/ethereum.h
- firmware/fsm.c
- firmware/fsm.h
Implements issue trezor/trezor-mcu#163.
> Ethereum Sign/Verify Message

- gen/strwidth.c
Simple tool to check the width of strings (for development purposes)
```bash
gcc strwidth.c fonts.c -o strwidth -lreadline
```
> Add strwidth tool

- oled.c
- oled.h
Get rid of the macros to access pixels.  Use only the functions instead.
Simplified some of the drawing functions.
> Clean-up of oled code.

- firmware/coins-gen.py
- firmware/coins.c
- firmware/coins.h
- firmware/protob/messages.options
- firmware/protob/messages.pb.h
- firmware/protob/types.pb.c
- firmware/protob/types.pb.h
- firmware/signing.c
- firmware/transaction.c
- firmware/transaction.h
* Add `SIGHASH_FORKID` replay protection (requires `amount` in `TxInputType`)
* Add Bitcoin Cash support
trezor/trezor-common#37
> Bitcoin Cash

- firmware/protect.c
If pin failure counter is too large wipe device instead of waiting and checking for PIN (in case the wipe after the last try failed.
> Fix check for max try and add another check before checking the PIN.

- buttons.h
Need this for a project :wink:
> Wrap button GPIO macros with #ifndef

- firmware/ethereum.c
This pull request is not ready to be merged yet, but I want to put it here to not forget it.
The multi-byte chain-id is still untested.  When testing it, I found out, Musicoin doesn't support EIP-155 at all and will sign transactions that are not replay protected.  Also Musicoin doesn't have a BIP-44 id so it would be dangerous to use it with Trezor.  So I'd suggest to either remove the Musicoin case or convince them that they have to use EIP-155 and need a  BIP-44 prefix :)
BIP-44 prefixes for Expanse and UBIQ are not that well supported in myetherwallet.  I think it uses them by default, but there is no bullet point in the dialog to select them explicitly.  This is an issue of mew and its hardware wallet integration, though.
It looks like some geth local test configuration uses a …
> Support multi-byte chain-id.

- firmware/fsm.c
- firmware/nem2.c
- firmware/nem2.h
- firmware/protob/types.options
Requires trezor/trezor-common#46 and trezor/trezor-crypto#114
> NEM Importance Transfer Transaction Support

- firmware/signing.c
There was a signed/unsigned problem: size_t is unsigned, but we use
-1 to indicate mismatch.  The problem was that when checking the input
address path, it still did this unintentionally when a mismatch was
detected, forbidding to sign with mismatched inputs, even when there
is no change address.
We now use 1 for mismatch.  Also we don't allow change address anymore
if the inputs have a path of length 1.  This simplifies the code a bit.
This fixes #226
> Fix checking change address

- firmware/reset.c
> Commit storage after initialization

- firmware/signing.c
Tiny typo based on the trezor/community gitter discussion
> signing segwit change output typo

- firmware/layout2.c
> Not encoding but encrypting typo

- bootloader/usb.c
- firmware/messages.c
- firmware/protect.c
- firmware/u2f.c
- firmware/usb.c
- memory.ld
- memory_app_1.0.0.ld
- memory_app_fastflash.ld
- setup.c
These are some older changes that somehow got lost.
> Some more confidential macros, bootloader flash order

- firmware/storage.c
- firmware/storage.h
- firmware/u2f.c
Fixes #251.
Depends on trezor/trezor-common#64
> Added U2F root key to storage.

- firmware/fsm.c
- firmware/fsm.h
- firmware/protob/messages.options
- firmware/protob/types.options
Requires trezor/trezor-common#65
> Add NEM message decryption

- Makefile.include
- firmware/storage.c
- firmware/transaction.c
> Fix uninitialized read in compile_output

- firmware/fsm.c
> Abort GetAddress on Initialize or Cancel

- firmware/storage.c
https://github.com/trezor/trezor-mcu/commit/d7de064bde0edb77f6198fddf3d016bb3b42caa1
> storage: next firmware version would be 1.7.0

- build-firmware.sh
> Fix building firmware in docker

- bootloader/usb.c
- firmware/crypto.c
- firmware/fsm.c
- firmware/messages.c
- firmware/pinmatrix.c
See #279 and trezor/trezor-crypto#141.
> Fix shift overflow

- emulator/oled.c
Makes emulator usable in containers
> Emulator: allow software renderer

- firmware/coin_info.py
> Prepend space to coin_shortcut

- firmware/Makefile
- firmware/fsm.c
- firmware/fsm.h
- firmware/protob/messages.options
- firmware/protob/types.options
- firmware/stellar.c
- firmware/stellar.h
This is a work in progress to add support for Stellar to the Trezor.
Implemented:
* Retrieve public address from BIP32 path
* Parses transaction header and displays confirmation UI to the user
* Parses payment operation and displays confirmation UI to the user
Not implemented yet:
* Remaining operations (see: https://www.stellar.org/developers/guides/concepts/list-of-operations.html)
* Documentation
I'm submitting this now for initial feedback and will continue to work on the additional operations.
**Implementation**
Stellar signing works by sending a stream of bytes from a client (such as the python `trezorctl`) to the Trezor:
1. Client sends first 1024 bytes of the transaction
2. Trezor parses the transaction header and confirms the details with the user
3. Trezor responds to the client …
> [Stellar] [WIP] Add support for Stellar

- .travis.yml
- Pipfile
- Pipfile.lock
- script/test
and set TREZOR_PATH to always pick the right device on first try
> ensure stable test environment with pipenv

- firmware/ethereum.c
WIP
Please see https://github.com/trezor/trezor-common/pull/149
> Ethersocial Network (ESN) support added

- firmware/ethereum.c
bitcointalk ANN    : https://bitcointalk.org/index.php?topic=2844280.0
homepage           : https://akroma.io
block explorer     : https://akroma.io/explorer
network statistics : http://stats.akroma.io
slip0044 index     : 200625 - https://github.com/satoshilabs/slips/pull/326 (recently merged)
chainId            : 200625
depends-on: https://github.com/trezor/trezor-mcu/pull/381 (already merged - thank you!)
depends-on: https://github.com/trezor/trezor-common/pull/177
relates-to: https://github.com/akroma-project/akroma-wallet-web/issues/9
cc: @detroitpro
> Add Akroma support

- firmware/ethereum.c
homepage           : https://musicoin.org
block explorer     : https://explorer.musicoin.org
slip0044 index     : 184
chainId            : 7762959
depends-on: https://github.com/trezor/trezor-common/pull/182
> Add Musicoin support

- Makefile.include
- emulator/setup.c
Compiling with the variable USE_RANDOM=1 will use /dev/random as random generator. Otherwise, the default is kept to /dev/urandom.
> Support /dev/random at compile time. Default is still /dev/urandom.

- emulator/oled.c
Setting the environment variable TREZOR_OLED_FULLSCREEN to non-zero activate that mode.
> Added fullscreen mode for emulator.
