trezor/trezor-mcu

firmware/layout2.c

Some QR scanners (javascript one, the app "QR Code Reader" or something like that on Android) have problems with transponed QR code. Trezor is generating transponed QR => I am correcting that
(it is not a nice fix but I am not sure how exactly the painting functions work to investigate further, also it's not a critical code so it doesn't really matter that much)

correcting transponed QR code

---

Makefile.include

The trezor-crypto code has some assertions, which are enabled unless
compiled with -DNDEBUG.  This does not make much sense for the Trezor
as could not write the assertion errors to stderr anyway.
This simple patch removes the dependency to assert, printf, etc. It
saves about 11kb flash and 2.2kb ram.

Disable assertion checking

---

firmware/protect.c
firmware/storage.c
firmware/storage.h

This diff contains three changes.
1. Make timing isPinCorrect independent of storage.pin, to avoid timing attacks
2. Only update failed PIN counter if the user entered a PIN.
Of course, the fail counter is still incremented, before the PIN is checked.
3. Don't cache the PIN, but just the fact that the PIN was entered.  The
cache should be in sync with storage.pin in any case.

PIN handling - constant time.

---

firmware-docker-build.sh

This all started with selinux denying output creation unless the output folder has security context type svirt_sandbox_file_t. Then cleaned up output filename a little bit.

Put firmware files in output/ and name them with the tag built

---

firmware/storage.c

Call to pbkdf2_hmac_sha512() uses salt string pointer argument (“TREZORHD”), which is located in ROM memory.  But pbkdf2_hmac_sha512() is expecting the pointer from RAM as it modifies the content. Actual salt value being used ends up being 
“TREZORHD\0Sta” as the attempt to modify it fails, (also producing a flash error flag to be set).

fixed salt passing to pbkdf2_hmac_sha512

---

firmware/protect.c
firmware/usb.c
firmware/usb.h

Added usbDelay that polls usb port (for system requests) while delaying. This is called instead of delay in the button and pin delay functions. Experimental evaluation gave that the cycle count should be roughly divided by 28.5.
This patch fixes the problem where TREZOR gets unresponsive after python-trezor was used and there was a long delay between button presses.

New usbDelay that delays and handles USB requests

---

firmware-docker-build.sh

reverting to the original version of `firmware-docker-build.sh`.

firmware-docker-build: revert branch and repository selection

---

firmware/pinmatrix.c
firmware/recovery.c
firmware/reset.c

These functions are called only by `fsm_msgDebugLinkGetState()`, which is excluded from release build.

firmware: exclude debug functionality from release build

---

firmware/crypto.c
firmware/crypto.h
firmware/fsm.c

This should allow GPG signature creation with TREZOR.
See https://github.com/romanz/trezor-agent/issues/3 for more details.

Add GPG v2.1 support by signing message digest

---

firmware/protect.c
firmware/storage.c
firmware/storage.h

Instead of reflashing the whole storage, we use a designated area
in the second storage block, where we mark each PIN failure by a
single zero bit. This is because one can set bits in flash to zero but
not to one.  If the PIN was entered successfully the whole word is
set to zero and the next word stores the new PIN failure counter.

Don't reflash storage after each PIN entry

---

firmware/protect.c

See issue #67.
If the countdown for PIN failures is running and an initialize comes in, abort the countdown and cancel PIN entry.

Allow initialize() to abort PIN wait

---

firmware/crypto.c
firmware/crypto.h

This will allow to implement ECDH support for GPG 2.1+, after https://github.com/trezor/trezor-common/pull/12 is merged.
See https://github.com/trezor/trezor-mcu/issues/85 for more details.

crypto: add ECDH session key generation

---

firmware/fsm.c
firmware/fsm.h
firmware/messages.c

I was not sure about the correct way to confirm the ECDH session key generation (see the comment at line 787), so currently it uses PIN-based protection only, similar to the `GetPublicKey` API.

Add ECDH support to TREZOR API

---

firmware/crypto.c
firmware/crypto.h
firmware/fsm.c
firmware/signing.c
firmware/storage.c
firmware/transaction.c

This is the second half of pull request trezor/trezor-crypto#61.  This changes the firmware to compute the public key where necessary and compute the fingerprint of the parent public key as required to produces BIP32 compatible xpub keys.
I'm not so happy with the way ed25519 public keys are handled.  I think they should be returned as 32 byte keys, but I didn't want to change the API without discussion and it would also break unit tests in python-trezor.  For backward compatibility I now replace the new 01 prefix in these public keys back to 00 again.

Only compute pubkey on demand.

---

Dockerfile

I wanted to use `make sign` inside the container and found this dependency to be missing.

add python-ecdsa dependency

---

oled.c
setup.c

Reopening after fixing the bug (thanks @spudowiar)
According to specs, the display can handle up to 10 MHz SPI traffic
(minimum cycle time is 100 ns). This patch sets the SPI port to
7.5 MHz (60 MHz clock with divisor 8).  In my tests the display works
even fine with SPI frequency at 60 MHz.  I also minimized the delays
(the spec doesn't require a long setup time) and use the registers to
check when transfer is done instead of using a fixed delay.  This is the 
procedure suggested by the STM32F2 manual.
This patch also changes the swipe function to swipe pixel by pixel.
Otherwise, the swipe would happen too fast to be seen.
This changes the display update time from 11 ms to 1.5 ms.

Faster SPI communication

---

firmware/coins.c

Address prefix is 'T' (uppercase) so address byte is 65 (decimal).
It was not clear from the CoinType protobuf definition what the byte 0x18 or 0x19 before the signed message represented.  Since only Bitcoin uses 0x18 and all others use 0x19, this patch uses 0x19.  Please change where appropriate.

Update coins.c for Zcash mainnet

---

firmware/crypto.c
firmware/ethereum.c
firmware/signing.c
firmware/u2f.c

This is the second part of the rfc6979 signing patch.  It must be applied together with the corresponding patch in trezor-crypto.
New parameter is_canonical that allows for generating signatures that
have additional requirements.

Reworked rfc6979 signing.

---

Makefile.include
firmware/Makefile
firmware/crypto.c
firmware/crypto.h
firmware/fsm.c

This PR depends on https://github.com/trezor/trezor-crypto/pull/74.
Usage example (using the latest version of https://github.com/romanz/trezor-agent/pull/51):
```
$ export TREZOR_GPG_USER_ID="testing1"
$ trezor-gpg create -e ed25519 | gpg2 --import
$ gpg2 -k
pub   ed25519 2016-10-15 [SC]
404376483FF50B280DE488BF7A16540A8435DBE7
uid           [ultimate] testing1
sub   cv25519 2016-10-15 [E]
$ trezor-gpg agent &
$ echo "Hello World!" | gpg2 --sign | gpg2 --verify
gpg: Signature made Sat 15 Oct 2016 03:51:26 PM IDT
gpg:                using EDDSA key 7A16540A8435DBE7
gpg: Good signature from "testing1" [ultimate]
$ date | gpg2 --encrypt -r "${TREZOR_GPG_USER_ID}" | gpg2 --decrypt
gpg: encrypted with 256-bit ECDH key, ID CDA4FB36AC6FDFDD, created 2016-10-15
"testing1"
Sat Oct 15 15:51:31 IDT …
```

Adding Curve25519 ECDH support for GPG decryption

---

firmware/layout2.c

Following ECDH usage of layoutDecryptIdentity (which shows "GPG decrypt for:" when used for ECDH) this commit adds a specific case for layoutSignIdentity, showing "GPG sign for:", instead of "GPG login to:" (which is less appropriate in the GPG context).

Add specific layout for GPG signature

---

Makefile
firmware/layout2.c
firmware/protect.c
firmware/storage.c
firmware/trezor.c
firmware/usb.c
timer.c
timer.h

SysTick timers provide efficient and incredibly accurate timings. This pull request removes `usbDelay(uint32_t cycles)` in favour of `usbSleep(uint32_t millis)` which is implemented with the aforementioned SysTick timers.

Use Cortex-M3 SysTick timers

---

firmware/layout2.c
firmware/trezor.c
firmware/usb.c
timer.c
timer.h

Every 4294967295 milliseconds (2 ^ 32 - 1), `system_millis` will overflow.
This means that every 49.71 days, `system_millis` will reset to zero.
Comparisons like `system_millis < (system_millis + 1)` would fail if the
latter had overflown and the former had not.
This is non-critical because the worst case is that one second could be
skipped or the screen could lock early.
This poses no threat to the exponential backoff used for protection
against brute force.
Thanks to @jhoenicke for the provided solution :heart:

timer: Fix non-critical integer overflow

---

firmware/debug.c
firmware/debug.h
firmware/trezor.c
firmware/u2f.c

`DEBUG_LINK` has a lot of side effects but was necessary for `DEBUG_LOG`
* Allow `DEBUG_LOG` without `DEBUG_LINK`
* Move `debugInt()` to `debug.c`

Improve debugging API

---

firmware/usb.c

Found at https://travis-ci.org/trezor/trezor-mcu/builds/187775326#L957

usb: exclude hid_report_descriptor_debug from non-debug build

---

firmware/u2f.c

We generate only U2F keys with hardened derivation.  However, we
didn't check incoming keys if they used hardened derivation.
This patch fixes this.

Check that U2F key only uses hardened derivation

---

Makefile.include

* Makes `upload` recipe depend on `sign` recipe

Build and sign before flashing to TREZOR

---

firmware/layout2.c

Following https://github.com/romanz/trezor-agent/issues/80, it should help displaying long GPG user IDs.

layout: split "First Last <first@last.com>" GPG user ID for readability

---

memory.c

Hi, based on the [hardware BOM](https://doc.satoshilabs.com/trezor-tech/hardware.html) that lists STM32F205RE as the MCU being used, I reviewed the bootloader protection code this morning.
I'm proposing some updates to not set reserved bits (which may lead to undefined behavior?) and to remove an unnecessary call to `flash_unlock_option_bytes` see also: https://github.com/libopencm3/libopencm3/blob/master/lib/stm32/common/flash_common_f24.c#L402-L413
I also added references to the manual that explains more about what is going on. I have not tested this code, so, please review.

memory protection: do not write reserved bits

---

firmware/usb.c

* Replace hard coded USB string identifiers with `enum`
* Annotate interfaces with human readable names

Clean up USB strings

---

bootloader/bootloader.c
demo/demo.c
firmware/trezor.c
setup.c

Here's a patch to address #150. It needs review and testing, especially since it changes the bootloader and I'm coding while sleepy.
The only thing that may be surprising is that I removed the call to setup and oledInit at the beginning of the firmware. My reason for doing so is that the bootloader already handles those things.
My basic firmware tests of this patch passed, but I'll do some more testing tomorrow.

fix issue #150

---

bootloader/signatures.c

This fixes the problem where the wrong hash is shown, if the firmware contains no signing key indices.

Compute hash before checking signatures.

---

firmware/coins-gen.py
firmware/coins.c
firmware/fsm.c
firmware/protob/messages.options
firmware/protob/messages.pb.c
firmware/protob/messages.pb.h

The `GetPublicKey` call takes an additional `coin_name` parameter, looks up the `xpub_magic` value and and passes it on to `hdnode_serialize_public`.

GetPublicKey altcoin support

---

firmware/Makefile
firmware/transaction.c

Can't take all the credit for this, it was detected by GCC 7.1.0

Fix buffer overflow in transaction.c

---

Makefile.include

This fixes a bug with Ubuntu 17.04.
It includes the correct architecture (armv7-m) and also includes the flag -mfix-cortex-m3-ldrd as default.

Set -mcpu=cortex-m3 linker flag.

---

firmware/fsm.c
firmware/recovery.c
firmware/recovery.h

This would allow safe mnemonic validation by using a dry-run flag (following https://github.com/trezor/trezor-mcu/issues/59).
**NOTE**: this PR requires re-generating protobuf-related code after https://github.com/trezor/trezor-common/pull/33 is merged.

Allow testing recovery with an initialized device

---

.travis.yml
bootloader/Makefile
bootloader/bootloader.c
fastflash/Makefile
fastflash/bootloader.c
fastflash/signatures.c
fastflash/usb.c
firmware/Makefile
firmware/fastflash.c
firmware/fastflash.h
firmware/trezor.c
memory_app_2.0.0.ld
memory_app_fastflash.ld

Add second bootloader support to enable faster flashing of firmware. This is similar to @jhoenicke's [`bootloaderhack`](https://github.com/jhoenicke/trezor-mcu/tree/bootloaderhack), but has a few advantages
* It does not affect normal builds of the firmware or the bootloader (so it can be merged into `master`)
* ~~The linker script reserves exactly the size of the bootloader~~ (not compatible with GCC 4.9.3)
* The linker script avoids use of magic constants (more avoidance is possible but it breaks compatibility with GCC 4.9.3)
* The linker verifies that the bootloader fits into the reserved space
* The bootloader does not waste time verifying the signatures (and unconditionally wipes the metadata)

Second bootloader support (fastflash)

---

firmware/recovery.c

Note: I wasn't sure whether to use `MEMSET_BZERO` macro (from `trezor-crypto`) or just plain `memset` (since most of the `trezor-mcu` code uses it).

recovery: zero new_mnemonic memory before returning to the user

---

Makefile.include
memory.c

This PR adds the ability for developers to easily compile a bootloader that won't lock the bootloader flash memory sectors on their dev board :)
The default is still to lock them. This is just a manual override.
verified the generated code with:
```
make clean && make && arm-none-eabi-objdump -d memory.o
make clean && make MEMORY_PROTECT=1 && arm-none-eabi-objdump -d memory.o
make clean && make MEMORY_PROTECT=0 && arm-none-eabi-objdump -d memory.o
```

add ability for developers to easily avoid locking their flash memory

---

bootloader/bootloader.c

My compiler was generating this code for the load_app function with the stack protector on:
```
|0x80002e4 <load_app>    push   {r0, r1, r2, lr}                                                                                                    │
│0x80002e6 <load_app+2>  ldr    r3, [pc, #40]   ; (0x8000310 <load_app+44>)                                                                         │
│0x80002e8 <load_app+4>  ldr    r1, [pc, #40]   ; (0x8000314 <load_app+48>)                                                                         │
│0x80002ea <load_app+6>  ldr    r2, [r3, #0]                                                                                                        │
│0x80002ec <load_app+8>  str    r2, [sp, #4] …
```

fix bootloader stack protector fault

---

bootloader/bootloader.c
firmware/fastflash.c
timer.c
timer.h
util.h

Removes duplicate code and uses a more idomatic method of loading the vector table.

Move bootloader and fastflash code to load_vector_table function

---

firmware/transaction.c

This is the correct fix for 09917920ba313da4dcdc7c64d47b014440bf822d
(how the code was meant to be written).

Fixed array sizes again.

---

Makefile.include
firmware/fsm.c
rng.c
setup.c

**High level info:**
This PR fixes hangs that are a result of how function `random32` mis-interprets (stale) RNG peripheral status.
Reference #153. This is the same fundamental problem. I closed #153  last time because it didn't seem to have momentum for getting merged. This time, I actually have experienced the hangs, can reproduce them, and have runtime gdb backtrace and register proof.
These device hangs can manifest themselves during signing messages, displaying number pads, resetting the device, switching between coins in the web wallet GUI, or simply booting up. I've experienced all of the aforementioned issues and tracked them to this single root cause.
**About the changes:**
1) first, this change does not set the interrupt enable bit in the rng control register. currently, the …

fix hangs due to using stale rng status

---

firmware/fsm.c

`protectButton` can call `fsm_msgDebugLinkGetState` in tiny mode, which uses `RESP_INIT`. This wipes the response to the original message.
Normally `protectButton` is called before writing to `resp` so this is not a visible issue. However, messages such as `GetAddress` call `protectButton` after.

Do not wipe msg_resp in DebugLinkGetState

---

firmware/coins.h
firmware/protob/messages.options
firmware/protob/messages.pb.h

Prevents silent crash in `fsm_msgGetFeatures` if `Features.coins` `max_count` is not large enough. Feel free to change the `_Static_assert` message.
/cc @jhoenicke

Assert that Features.coins max_count is large enough

---

.travis.yml
firmware/Makefile

This should catch inconsistencies with `Features.coins` or if there is a
build configuration that makes the firmware too large.
Also, add `MAKEFLAGS` and only build `STM32F2` support in `libopencm3` to
speed up build time

Test matrix of DEBUG_LINK and FASTFLASH

---

.travis.yml
build-bootloader.sh
build-firmware.sh

Cleanup the build output:
```
In file included from ../cm3/../dispatch/vector_chipset.c:14:0,
from ../cm3/vector.c:25:
../cm3/../dispatch/../vf6xx/vector_chipset.c: In function 'pre_main':
../cm3/../dispatch/../vf6xx/vector_chipset.c:30:2: warning: implicit declaration of function 'asm' [-Wimplicit-function-declaration]
asm ( \
^~~
```
This is fixed by:
https://github.com/libopencm3/libopencm3/commit/f3df01f14e90849caa821ccda8ade6c953085964
Also, libopencm3 has gone to c99:
https://github.com/libopencm3/libopencm3/commit/b86031978553ca3d6dd1eb9015c2d5ea4cdd8794
`git submodule update --remote vendor/libopencm3/`
updates from `b76d853a723d39bbc083495bb7460cf3f071476c` to `b0e050d10d12c42be031c34822117cfd3c5a0ea7`
`git diff b76d853a723d39bbc083495bb7460cf3f071476c …

cleanup build, update libopencm3

---

memory.c

I don't think this is urgent. This is more to be complete with the recommendations of some newly published research: https://www.usenix.org/system/files/conference/woot17/woot17-paper-obermaier.pdf
Section 3.2.4 on countermeasures: "This includes the “read protection level status” in the FLASH OBR register as well as the option bytes themselves."
FLASH_OPTCR is the f2 family equivalent flash interface register.
I was thinking of masking off the two low bits in my comparison, but then decided to go with the simple equality test because the option lock seems like it should always be set, and we should not be in the midst of an update to the option bytes, when making this check.

memory_protect: add flash interface register check

---

.gitmodules
Dockerfile
build-firmware.sh
firmware/protob/Makefile

This is so as to improve the build reliability by ensuring protobuf files are generated at build time, to make life easier for future maintainers, and reduce ceremony of generating files and checking them in.
I've not been so opinionated as to remove the generated files from the repo as they get clobbered during the generation, but I do actually think it's a reasonable idea because it's very unambiguous that the developer should not hand-maintain them - if you comment on the PR that you would like this, I can add it to the change set.
Some notes: 
- I've pinned the nanopb submodule to the version that originally generated the files (0.2.9.3).
- In testing, I can confirm the files generated are identical down to the byte, to those presently in the repo.
I'd like to automate the generation …

Generate the protobuf files at build time

---

Makefile.include
firmware/.gitignore
firmware/Makefile
firmware/coins-gen.py
firmware/coins.c
firmware/coins.h
firmware/coins.json
firmware/protob/Makefile

This generates the coins.h and coins.c files from coins.json source at build time, to help ensure consistency.
Previously it was reliant upon the user to run coins-gen.py manually and hand-edit the coins.h and coins.c files.
I'm checking the two new generated files in here `coins_array.h` and `coins_count.h`, however that is just for illustration - the build process clobbers them consistently.

Generate coins.h and coins.c source code at build time

---

Makefile.include
firmware/Makefile

Generate dependency files before the build (so we do not have to specify generated header file dependencies manually)
* `-MP` is used to generate empty rules for header files (so we don't have to remove stale `.d` files if a header file is deleted)
* `-MG` is used to make GCC ignore missing header files (so we can create dependencies on generated header files such as `nem_mosaics.h`)

Makefile.include: Generate dependency files before build

---

firmware/layout2.c
firmware/layout2.h
firmware/pinmatrix.c

This greatly reduces the amount of time that device tests take. With SegWit native device test, it reduced the time by 40%.

Disable swipe with DEBUG_LINK

---

firmware/coins-gen.py
firmware/coins.c
firmware/coins.h
firmware/crypto.c
firmware/crypto.h
firmware/fsm.c
firmware/layout2.c
firmware/layout2.h
firmware/signing.c
firmware/signing.h
firmware/transaction.c
firmware/transaction.h

Having CoinType using the protobuf structures has several disadvantages.
- We always need to change trezor-common if we need a new field (like bech32 prefix)
- Every time Trezor initializes it sends all this information out and nobody cares.
- The protobuf structures add storage overhead due to their fixed size.
I also removed some of the `has_` fields:
- `has_segwit` and `segwit` are now merged.
- `has_coin_shortcut` can be replaced by test for NULL if necessary.

New CoinInfo separated from protobuf structures

---

firmware/coins-gen.py
firmware/coins.h
firmware/fsm.c
firmware/protob/messages.options
firmware/signing.c
firmware/transaction.c
firmware/transaction.h

This is not tested against Bitcoin Gold but it has not broken Bitcoin or Bitcoin Cash. All hardcoded instances of `SIGHASH_ALL` have been removed.
/cc @jhoenicke

Enable SIGHASH_FORKID for SIGVERSION_BASE and SegWit

---

firmware/crypto.h
firmware/signing.c
firmware/transaction.c
firmware/transaction.h

Fixes issue #232.
**Note**: This patch displays the size estimate on the TREZOR display for debugging purposes.  I intend to remove this later.   It is ready for review/testing,  but I want to remove this before merging.
It assumes largest possible signature size for all inputs.  For segwit multisig it can show a .25 bytes larger value per input due to difference between segwit encoding (varint) vs. non-segwit encoding (op_push) of the multisig script. The segwit discount is included in the calculations.

Byte-precise size estimate for fees

---

firmware/Makefile
firmware/coins-gen.py
firmware/coins.h
firmware/crypto.c
firmware/crypto.h
firmware/hasher.c
firmware/hasher.h
firmware/signing.c
firmware/signing.h
firmware/transaction.c
firmware/transaction.h

Rewrite Bitcoin transaction signing to support other hash algorithms. This is useful for coins like Decred, which uses BLAKE256 instead of SHA256.
The only remaining SHA256 specific code in the transaction signing is the `ecdsa_get_pubkeyhash` and `ecdsa_get_address_*` calls.
All device tests pass.
/cc @peterzen

Generic hash support for Bitcoin transactions

---

firmware/fsm.c
firmware/protect.c
firmware/recovery.c
firmware/reset.c
firmware/storage.c
firmware/storage.h
firmware/trezor.c

- Don't copy storage from Flash to RAM.
- Use accessor functions for storage.
- New update logic to only update changed fields.

Storage rework

---

firmware/protob/messages.options

`vendor/trezor-common` was updated in 9732825e243548b20f9c617718333a6d359970b5 which breaks `DEBUG_LINK=1` builds because it includes `Decred Testnet`.

Increase Features.coins max_count

---

firmware/fsm.c
firmware/fsm.h

This is especially useful for debugging the signing code (`Transaction has changed during signing` is not the most useful message!)
Should this be behind `DEBUG_LINK`? It shouldn't break anything (as the tests use the `FailureType`). If not behind `DEBUG_LINK`, we could add a `DEBUG_FSM` or similar flag (`DEBUG_LOG` is definitely not the right place for this)

Include file and line in Failure for DEBUG_LINK

---

firmware/fsm.c

On small screen I was confused what "msig" said.  Thought it was "message"
Should be plenty of room

enhace description of multisig label

---

emulator/strl.c

I implemented the return semantics of `strlcpy` incorrectly. This doesn't affect anything because we never use the return value.

Fix emulator strlcpy implementation

---

firmware/trezor.c
setup.c
setup.h

Disable code execution from SRAM and reconfiguration of the MPU.
Prevents almost all code execution attacks.

Enable MPU

---

firmware/trezor.c
setup.c
util.h

All tests pass.
Attempts to write to the System Control Space cause a hard fault (perhaps there's a more specific fault handler we can enable for this?)

Switch to unprivileged execution and prevent access to MPU

---

emulator/strl.c

Performance is unimportant and this implementation makes it easier to fuzz (with ASan, etc.)

Refactor strlcpy for emulator

---

Dockerfile.emulator
README.md
build-emulator.sh

I have added emulator build to docker.
Note that it requires changes from https://github.com/trezor/trezor-mcu/pull/301 
The readme mentions env variable from this PR https://github.com/trezor/trezor-mcu/pull/302

Add docker build script 

---

Makefile.include

Fixing makefile for non-headless emulator.
Taken from @jhoenicke PR here https://github.com/trezor/trezor-mcu/pull/295 (thx @saleemrashid for tip)
for some reason, git reversed which part of Makefile is actually moved :))

Fixing emulator makefile

---

Dockerfile.emulator
build-emulator.sh

As discussed in https://github.com/trezor/trezor-mcu/pull/303

emulator: Removing useless build and install

---

firmware/signing.c

- Allow change address to be on the receive chain (..../0/x) (see spesmilo/electrum#3920).
- Allow more than one output to the Trezor, but don't treat it as change.

Less paranoid change outputs.

---

firmware/layout2.c

If the destination address is controlled by the TREZOR (the wallet set
the address_n field), show the path to the address on the confirm output
dialog in the same format as the "show on Trezor" dialog indicates the
path.
This is useful when claiming coins or sending from legacy to segwit wallet (provided the tool supports it). 
[The patch is a bit larger, because I had to move the `address_n_str` function to the beginning. I didn't change anything in there.]

Indicate own dest address in send dialog

---

Makefile.include
bootloader/bootloader.c
bootloader/usb.c
emulator/emulator.h
emulator/flash.c
emulator/setup.c
firmware/fsm.c
firmware/protect.c
firmware/storage.c
firmware/storage.h
memory.c
memory.h
script/cibuild

Use `FLASH_PTR` macro to convert a flash address to a const pointer.
For real hardware it is just a cast, for emulator we subtract the `FLASH_ORIGIN` and use it as index into the memory mapped flash file.
This makes the emulator run with 64-bit builds as it avoids direct casts from 32 bit numbers to pointers.

Cleaner flash handling using FLASH_PTR

---

firmware/nem2.c

See discussion https://github.com/trezor/trezor-mcu/commit/17e33d5517b0dd08c268d569b108a8c3484275de#r28307250
cc @saleemrashid

nem: SignTx instead of ConfirmOutput in mosaic creation

---

Dockerfile.emulator
build-emulator.sh

Emulator is a 64-bit application now, so we should install 64-bit version of libSDL. Rename docker image and emulator filename to indicate 64-bitness as well.

Fix emulator build in docker

---

firmware/nem2.c

The IV copy was moved to trezor-crypto
(https://github.com/trezor/trezor-crypto/pull/140) so it is not needed
in trezor-mcu anymore

nem: IV is not copied before encryption (moved to trezor-crypto)

---

startup.s

In trezor-core we call shutdown when main returns. Let's do the same here.
One question: is the proposed patch OK, or it's better to let the code fall through? (because shutdown label is directly 4 lines below)

startup: shutdown at end instead of loop

---

firmware/fsm_msg_common.h

The message is very confusing, as it is not recovering the device. Since dry-run recovery does not change anything, there is no need to ask for confirmation.

Recovery: Don't ask for confirmation on dry run.

---

firmware/bl_check.c
firmware/trezor.c
util.h

Only drop privileges if firmware is running with privileges.
Don't change the bootloader if running without privileges.
With this change the firmware can run without being signed.

Check if firmware has privileges.

---

firmware/Makefile
firmware/fsm.c
firmware/fsm_msg_stellar.h
firmware/protob/Makefile
firmware/protob/types.options
firmware/stellar.c
firmware/stellar.h

* Use the new protobuf messages that send accounts as strings (fixes #367)
* `stellar_signingAbort()` now takes an error message
* Operations now check if a transaction is being signed (fixes #368)
* Operations now return false on error or if the user cancels
* Stellar `fsm_*` methods now check operation result and return early if the operation fails
This PR also re-enables the stellar code in the firmware.

Stellar: use strings instead of bytes for addresses

---

script/fullbuild

`fullbuild` would previously fail if the parent repository hadn't initialized submodules yet, due to the use of `--reference`
06fbb91 fixes another issue (the use of nested submodules), but didn't fully fix this one.
Fixes #382

fullbuild: Call script/bootstrap before clone

---

firmware/ethereum.c

See also https://github.com/trezor/connect/issues/137

fixed rlp_length for chain_id > 255

---

emulator/flash.c

Even if the emulator flash file is opened with the O_SYNC flag, that doesn't guarantee that data is really flush out of hardware cache to persistant layer. This PR fix this.
Ref : https://thecodeartist.blogspot.com/2012/08/hdd-filesystems-osync.html

commit emulator flash modification to persistent storage

---

firmware/ethereum.c

* remove chain_id restriction to support full 32bit chain_id.
* for `chain_id > MAX_CHAIN_ID(2147483630)` case, simply return `v` signature parity.
with this fix Trezor can support full 32bit chain_id.
- *no backward compatible issue.*
- for chain_id > MAX_CHAIN_ID case, returned `v` is `0` or `1` and it can be easily detectable.
- for chain_id > MAX_CHAIN_ID case, one can easily recalculate `signature_v` at client side.
`chain_id` |`signature_v` | firmware| `v`
-----------|---------|-----------|----------------
no EIP155 case | `27`+ `v` (>= `27`) | `1.6.2`  | `1`, `0`
`1` <= `chain_id` <= `MAX_CHAIN_ID`      | 2 * `chain_id` + 35 + `v` (>= `37`) | `1.6.2`[*] [**]  | `1`, `0`
`chain_id` > `MAX_CHAIN_ID` | `v` ( <= `1`) | *detectable* | `1`, `0`
[*]: currently, official 1.6.2 firmware …

ethereum: support full range 32bit chain_id

---

firmware/ethereum.c

bitcointalk ANN    : https://bitcointalk.org/index.php?topic=2120193.0
homepage           : https://pirl.io
block explorer     : https://explorer.pirl.io | https://poseidon.pirl.io/explorer
network statistics : http://stats.pirl.io
slip0044 index     : 164
chainId            : 3125659152
depends-on: https://github.com/trezor/trezor-mcu/pull/399 (merged)
depends-on: https://github.com/trezor/trezor-core/pull/311 (merged)
depends-on: https://github.com/trezor/trezor-common/pull/193
see-also: https://github.com/trezor/python-trezor/pull/297
cc: @masterdubs @pirl

Add Pirl support

---

firmware/Makefile
firmware/fsm.c
firmware/fsm.h
firmware/fsm_msg_lisk.h
firmware/lisk.c
firmware/lisk.h
firmware/protob/Makefile
firmware/protob/messages-lisk.options
firmware/protob/messages-lisk.proto

This is a work in progress to add support for `Lisk` to the `trezor-mcu`.
Messages: https://github.com/trezor/trezor-common/pull/68
Trezor-pyton: https://github.com/trezor/python-trezor/pull/197
Progress:

Add Lisk support

---

Dockerfile
script/fullbuild

Fixes https://github.com/trezor/trezor-mcu/issues/410
With https://github.com/trezor/trezor-mcu/pull/411 , the docker build now works.

build: Use pipenv in docker build

---

emulator/strl.c
emulator/strl.h

Emulator doesn't build on macOS because macOS already has `strlcpy` and `strlcat`.

emulator: make buildable on macOS

---

Dockerfile

The docker build fails if the hash is incorrect.

Add sha256sum check to protobuf binaries in Dockerfile

---

firmware/config.c
firmware/fsm_msg_common.h

config: Check mnemonic by comparing hashes instead of the actual mnemonics, to mitigate side-channel attacks.

Secure mnemonic checking

---

firmware/config.c
firmware/config.h
firmware/fsm_msg_coin.h
firmware/fsm_msg_debug.h
firmware/protob/Makefile
firmware/protob/messages-debug.options

1. fixes tests with current trezor-common (there was a missing `set_node` flag because of https://github.com/trezor/trezor-common/commit/84f5a0e39376409863c58a9ede1b61403306894b)
2. introduces option to return mnemonic as bytes because debuglink now returns bytes (https://github.com/trezor/trezor-common/commit/c5e54d7535c8772b9a75ff90c506a28526f94267)

Return mnemonic as bytes

---

firmware/usb.c

Avoid segfault in usbSleep(), usbReconnect() and usbPoll() when USB is not initialized.
I am unable to test this fix, getting "Hard fault detected" during boot, however I get the same message even without this commit.

usb: Fix segfault in usbSleep().
